### ISSUE TITLE
ensembl-vep installation via conda fails

### ISSUE THREAD

**Issue by phoenix1391** [Ensembl/ensembl-vep#1102]
I am trying to install ensembl-vep from a conda environment. I cloned it from GitHub following the instructions in this link: https://m.ensembl.org/info/docs/tools/vep/script/vep_tutorial.html. Then I created a conda environment and installed Perl, perl modules, bioperl, gcc, and archive. From this conda environment I am trying to execute Install.pl but keep getting the error mentioned below. First, I tried without the --NO_HTSLIB tag but it resulted in some errors so I tried with the tag and received another error. Please help me understand if I am doing anything wrong here.

### System
- VEP version: v105 
- VEP Cache version: v105
- Perl version: 5.32.1
- OS: CentOS
- tabix installed: No

### Full VEP command line
```
perl INSTALL.pl
```

### Full error message
> Including the warnings, if available

Hello! This installer is configured to install v105 of the Ensembl API for use by the VEP.
It will not affect any existing installations of the Ensembl API that you may have.

It will also download and install cache files from Ensembl's FTP server.

Checking for installed versions of the Ensembl API...done

Setting up directories
Destination directory ./Bio already exists.
Do you want to overwrite it (if updating VEP this is probably OK) (y/n)? y
 - fetching BioPerl
 - unpacking ./Bio/tmp/release-1-6-924.zip
 - moving files

Downloading required Ensembl API files
 - fetching ensembl
 - unpacking ./Bio/tmp/ensembl.zip
 - moving files
 - getting version information
 - fetching ensembl-variation
 - unpacking ./Bio/tmp/ensembl-variation.zip
 - moving files
 - getting version information
 - fetching ensembl-funcgen
 - unpacking ./Bio/tmp/ensembl-funcgen.zip
[./Bio/tmp/ensembl-funcgen.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of ./Bio/tmp/ensembl-funcgen.zip or
        ./Bio/tmp/ensembl-funcgen.zip.zip, and cannot find ./Bio/tmp/ensembl-funcgen.zip.ZIP, period.
 - moving files
ERROR: Could not move the directory './Bio/tmp/ensembl-funcgen-release-105/modules/Bio/EnsEMBL/Funcgen'
No such file or directory at INSTALL.pl line 706.

**Comment by jamie-m-a** [comment]
Hi @phoenix1391 

I'm sorry to hear you're having trouble with the VEP install under conda.

I don't think you've done anything wrong, it looks as though the download of the compressed func-gen repo may have become corrupted and as a result the unzip process is producing an error. I have just tried to download and unzip it using the same link that is produced by the INSTALL.pl script and it works fine.

It might be easiest to clean up (delete) the current partial install and restart it. Alternatively you can specify a different installation directory using the -d option for INSTALL.pl

Hopefully this should resolve the problem, but do get back in touch if you're still having trouble with the installation.

**Comment by phoenix1391** [comment]
Hi @jamie-m-a, 

Thank you for helping me out in this. I was able to install vep without any further issues. However, it failed to download the cache files. I might need them in future for faster access. I was wondering if there is a way to download the cache files separately? 

Here is the error I received while getting the cache files:

```
 - getting list of available cache files
ERROR: Could not connect to FTP host ftp.ensembl.org
Connection timed out
```

Thanks!

**Comment by jamie-m-a** [comment]
Hi @phoenix1391 

Glad to hear you got it working. Possibly there was an intermittent issue with the connection, or it may be that you have a firewall preventing you downloading from the ftp. But you can try to manually download the cache files you want by following the instructions on this page: https://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html 

Let me know how you get on.

**Comment by phoenix1391** [comment]
Hi @jamie-m-a,

It was the firewall in my institution which was preventing me from downloading using FTP. I am trying from my home but I keep getting the following error:
```
curl: (18) transfer closed with 12913515445 bytes remaining to read
```
I did try with options 'Connection: keep-alive' and --keepalive-time but it still fails after sometime. Is it possible for you to suggest any other option? I am using the following now:

```
curl -O http://ftp.ensembl.org/pub/release-105/variation/indexed_vep_cache/homo_sapiens_vep_105_GRCh38.tar.gz -H 'Connection: keep-alive' --keepalive-time 30
```

**Comment by jamie-m-a** [comment]
Hi @phoenix1391 

So the caches aren't required in order to run VEP, though having them locally will speed up run time significantly. If the data you wish to annotate is relatively small (few thousand variants), you could try running with out the cache options.

I believe you can attempt to restart a stalled curl command using -C - 

So if you current command you're running fails, you can retry it using:

`curl -O -C - http://ftp.ensembl.org/pub/release-105/variation/indexed_vep_cache/homo_sapiens_vep_105_GRCh38.tar.gz -H 'Connection: keep-alive' --keepalive-time 30`

Which should restart it at the point it failed.

**Comment by jamie-m-a** [comment]
Hi @phoenix1391 

Yes, as you've probably already seen using --database is not compatible with --offline or caching option, a full description of the options available when running VEP can be found here: https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html 

If your institute has a more stable/faster internet access than on your personal machine, then I'd recommend using the manual download there instead, or possibly contacting your IT support to see if they can allow the ftp download that would have occurred as part of the install.

If that isn't an option, then perhaps you can use the web VEP service or the REST service, but both options are affected by how many variants you're trying to analyse. A few hundred or even few thousand is feasible to do this way, much larger than that and you're better off with the local install and cache.

**Comment by phoenix1391** [comment]
Thank you @jamie-m-a for providing me with all different options. I will contact my institute to see if they can allow me to download using ftp so that I can access it in a faster way.

**Comment by phoenix1391** [comment]
Hi @jamie-m-a, My institution agreed to make create an exception rule to allow downloading from this link. However, they need a source IP to set up this link. Is it possible to provide the source IP for the download of http://ftp.ensembl.org/pub/release-105/variation/indexed_vep_cache/homo_sapiens_vep_105_GRCh38.tar.gz? 

Thank you so much.

**Comment by jamie-m-a** [comment]
Hi @phoenix1391 

We're in touch with our IT service to confirm the externally facing IP for downloading that file - I should have the answer for you soon.

**Comment by jamie-m-a** [comment]
Hi @phoenix1391 

Sorry for the delay in responding: the following IP addresses should be added to the whitelist by your institution:

193.62.197.76
193.62.193.139

This should then allow the ftp download to work correctly.

I'll keep this ticket open for a while, in case you have any further issues with the download.

**Comment by phoenix1391** [comment]
Thank you @jamie-m-a for the IPs. I will report it to my institution and give you an update as soon as possible.

**Comment by phoenix1391** [comment]
Hi @jamie-m-a, I was able to donwload without any issues. Thank you so much for your help!

**Comment by MGCarta** [comment]
Hi @jamie-m-a, 
I´m dealing with VEP from several months and I never encountered any issues. 

However, now I need to run VEP faster. I´m annotating vcf files in --offline mode and when I tried to add --fork 4 in order to use more than one core I encountered this error:


-------------------- EXCEPTION --------------------
MSG: ERROR: Cache directory /home/carta/.vep/homo_sapiens not found

STACK Bio::EnsEMBL::VEP::CacheDir::dir /res/store/bio/miniconda3/envs/vep104/share/ensembl-vep-104.3-1/modules/Bio/EnsEMBL/VEP/CacheDir.pm:311
STACK Bio::EnsEMBL::VEP::CacheDir::init /res/store/bio/miniconda3/envs/vep104/share/ensembl-vep-104.3-1/modules/Bio/EnsEMBL/VEP/CacheDir.pm:227
STACK Bio::EnsEMBL::VEP::CacheDir::new /res/store/bio/miniconda3/envs/vep104/share/ensembl-vep-104.3-1/modules/Bio/EnsEMBL/VEP/CacheDir.pm:111
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all_from_cache /res/store/bio/miniconda3/envs/vep104/share/ensembl-vep-104.3-1/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:115
STACK Bio::EnsEMBL::VEP::AnnotationSourceAdaptor::get_all /res/store/bioi/miniconda3/envs/vep104/share/ensembl-vep-104.3-1/modules/Bio/EnsEMBL/VEP/AnnotationSourceAdaptor.pm:91
STACK Bio::EnsEMBL::VEP::BaseRunner::get_all_AnnotationSources /res/store/bio/miniconda3/envs/vep104/share/ensembl-vep-104.3-1/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:170
STACK Bio::EnsEMBL::VEP::Runner::init /res/store/bio/miniconda3/envs/vep104/share/ensembl-vep-104.3-1/modules/Bio/EnsEMBL/VEP/Runner.pm:128
STACK Bio::EnsEMBL::VEP::Runner::run /res/store/bio/miniconda3/envs/vep104/share/ensembl-vep-104.3-1/modules/Bio/EnsEMBL/VEP/Runner.pm:199
STACK toplevel /res/store/bio/miniconda3/envs/vep104/bin/vep:232
Date (localtime)    = Fri Feb  4 11:34:06 2022
Ensembl API version = 104
---------------------------------------------------

I installed ensembl-vep into a conda environment in my server, why is vep looking for genome reference file at that directory? At the beginning I installed ensembl-vep with the following command:

vep_install --NO_HTSLIB -c '/res/store/.vep' -r '/res/store/.vep/Plugins/' -a cfp -s homo_sapiens_refseq -y GRCh37 -g all

I hope I will get a feedback soon, thank you in advance. 
Giulia

**Comment by jamie-m-a** [comment]
Hi @phoenix1391 

That's great to hear! I'm going to close this issue now, but please to get in touch if you run into any further difficulties.
