### ISSUE TITLE
Confused by 'ERROR: No matching species found at INSTALL.pl line 1121.'

### ISSUE THREAD

**Issue by evanbiederstedt** [Ensembl/ensembl-vep#268]
I'm a bit confused by the error given when installing with the following:

```
perl INSTALL.pl --AUTO acf --SPECIES saccharomyces_cerevisiae --ASSEMBLY R64-1-1 --CACHEDIR $VEP_DATA
```

or 

```
perl INSTALL.pl --AUTO acf --SPECIES danio_rerio  --ASSEMBLY GRCz11 --CACHEDIR $VEP_DATA
```

Here is the error I receive:

```
ERROR: No matching species found at INSTALL.pl line 1121.
```

I suspect I'm doing something incorrect---a misspelling perhaps? Any help appreciated

**Comment by aparton** [comment]
Hi,

Do you have other ensembl repositories installed on your machine? This error message will show up if other ensembl API elements with different versions can be found in your $PATH.

If so, updating your other ensembl repos to the same version as VEP should fix this issue. If not, let me know and I can take a closer look.

Kind Regards,
Andrew

**Comment by evanbiederstedt** [comment]
Hello @at7 @aparton 

Thank you for the reply, I appreciate the help!

Hi Anja @at7

> I cannot reproduce the error when I run the same command. 

My Travis-CI builds should be accessible here: https://travis-ci.org/mskcc/vcf2maf/builds/

These replicate the errors I'm getting above. 

(A) For the command

```
perl INSTALL.pl --AUTO acf --SPECIES saccharomyces_cerevisiae --ASSEMBLY R64-1-1 --CACHEDIR $VEP_DATA
```

The configuration is here: https://github.com/mskcc/vcf2maf/blob/946cef470c86ce7c5d1170bee802d479a75a591e/.travis.yml
The build (with error) is here: https://travis-ci.org/mskcc/vcf2maf/jobs/419958445

(B) For the command

```
perl INSTALL.pl --AUTO acf --SPECIES danio_rerio  --ASSEMBLY GRCz11 --CACHEDIR $VEP_DATA
```

The configuration is here:  https://github.com/mskcc/vcf2maf/blob/0e09af54589996fb3bd5ffd679ac0b08f03af62e/.travis.yml
The build (with error) is here: https://travis-ci.org/mskcc/vcf2maf/builds/420145729


Hi Andrew @aparton 

> This error message will show up if other ensembl API elements with different versions can be found in your $PATH.

In the Travis-CI builds, I have done the following:

      - VEP_PATH=$HOME/vep VEP_DATA=$HOME/.vep VER=91 PERL5LIB=$VEP_PATH:$PERL5LIB PATH=$VEP_PATH/htslib:$PATH

It's not clear to me I'm mixing together different Ensembl API elements with this though...

**Comment by at7** [comment]
You are installing version 93 but you are setting VER to 91. I cannot see if VER is used anywhere.

**Comment by evanbiederstedt** [comment]
Hi @at7 

Thanks for the response. Your observation makes sense!

I'm still running into problems though it appears:

Here is the build with `VER` explicitly set as `VER=93`, with the error `ERROR: No matching species found at INSTALL.pl line 1121.`. 

Build with `VER` specified: 
https://travis-ci.org/mskcc/vcf2maf/jobs/421684447/config
Travis config:  
https://github.com/mskcc/vcf2maf/blob/develop/.travis.yml

```
env:
  - VEP_PATH=$HOME/vep VEP_DATA=$HOME/.vep VER=93 PERL5LIB=$VEP_PATH:$PERL5LIB PATH=$VEP_PATH/htslib:$PATH
perl INSTALL.pl --AUTO acf --SPECIES saccharomyces_cerevisiae --ASSEMBLY R64-1-1 --CACHEDIR $VEP_DATA
```


Build with no `VER` specified: 
https://travis-ci.org/mskcc/vcf2maf/jobs/421676609
Travis config:  https://github.com/mskcc/vcf2maf/blob/e531ac80637bd3c98e91cbcd7686cc071a76ee82/.travis.yml

```
env:
  - VEP_PATH=$HOME/vep VEP_DATA=$HOME/.vep PERL5LIB=$VEP_PATH:$PERL5LIB PATH=$VEP_PATH/htslib:$PATH

perl INSTALL.pl --AUTO acf --SPECIES saccharomyces_cerevisiae --ASSEMBLY R64-1-1 --CACHEDIR $VEP_DATA

```

I suspect I'm setting something up incorrectly? Any help appreciated

**Comment by at7** [comment]
I can reproduce the problem now: https://travis-ci.org/at7/vep-install/jobs/421958486
I thought it might have been a perl version error and tried with a different version but it is still failing: https://travis-ci.org/at7/vep-install/builds/421975364
There is probably more setup work required to get it run successfully. I need to do more investigating to see what else needs to be installed. You could have a look at the ensembl-vep travis file and see if you can reuse any of the code: https://github.com/Ensembl/ensembl-vep/blob/release/93/.travis.yml

**Comment by evanbiederstedt** [comment]
Hi @at7 

Thank you again for the help---much appreciated. 

> You could have a look at the ensembl-vep travis file and see if you can reuse any of the code: https://github.com/Ensembl/ensembl-vep/blob/release/93/.travis.yml

I'll try this out. In principle, if v93 builds successfully here, we could use these travis build settings

I will keep you updated; let me know if you figure anything out :)

**Comment by aparton** [comment]
Hiya,

We’ve had a look at this issue over the past couple of days and we can’t ascertain precisely what is going on with your setup. Could you please try and install VEP from the following fork and branch with your current setup, and send us the output? https://github.com/aparton/ensembl-vep/tree/rel93-installtest <https://github.com/aparton/ensembl-vep/tree/rel93-installtest>

This should hopefully allow us to work out why your setup cannot find the appropriate cache files.

Kind Regards,
Andrew

**Comment by evanbiederstedt** [comment]
Hi @aparton, @at7 

Thank you again for the help

> Could you please try and install VEP from the following fork and branch with your current setup, and send us the output? https://github.com/aparton/ensembl-vep/tree/rel93-installtest <https://github.com/aparton/ensembl-vep/tree/rel93-installtest>

So, here is the s. cerevisiae build, which fails:
build: https://travis-ci.org/mskcc/vcf2maf/builds/422202910
config: https://github.com/mskcc/vcf2maf/blob/s_cerevisiae/.travis.yml

```
ERROR: No matching species found at INSTALL.pl line 1123.
```

Here is the same config with the homo sapiens assembly:
build: https://travis-ci.org/mskcc/vcf2maf/builds/422192449
config: https://github.com/mskcc/vcf2maf/blob/develop/.travis.yml

**Comment by evanbiederstedt** [comment]
Hi @at7, @aparton 

Thanks for the help!

Here's the current state of the tests for `Testing VEP installation`:

(1)
homo sapiens:
build: https://travis-ci.org/mskcc/vcf2maf/builds/422269347
config:
https://github.com/mskcc/vcf2maf/blob/8c87d5490bf2cc81aacfbe90ba31840772cd384a/.travis.yml

Summary:

```
Test Summary Report
-------------------
./t/Runner.t                                       (Wstat: 65280 Tests: 73 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
Files=40, Tests=1652, 76 wallclock secs ( 0.34 usr  0.08 sys + 71.70 cusr  3.03 csys = 75.15 CPU)
Result: FAIL
Failed 1/40 test programs. 0/1652 subtests failed.
```

(2)
s. cerevisiae:
build: https://travis-ci.org/mskcc/vcf2maf/builds/422268933
config: https://github.com/mskcc/vcf2maf/blob/8c87d5490bf2cc81aacfbe90ba31840772cd384a/.travis.yml

```
Test Summary Report
-------------------
./t/Runner.t                                       (Wstat: 65280 Tests: 73 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
Files=40, Tests=1652, 73 wallclock secs ( 0.30 usr  0.14 sys + 69.31 cusr  2.80 csys = 72.55 CPU)
Result: FAIL
Failed 1/40 test programs. 0/1652 subtests failed.

```

**Comment by evanbiederstedt** [comment]
So, I do get the tests to pass without installing htslib first. 

s. cerevisiae:
build: https://travis-ci.org/mskcc/vcf2maf/builds/422268933
config: https://travis-ci.org/mskcc/vcf2maf/builds/422370957

```
All tests successful.
Files=40, Tests=1690, 86 wallclock secs ( 0.34 usr  0.10 sys + 82.95 cusr  3.50 csys = 86.89 CPU)
Result: PASS
 - OK!
 - getting list of available cache files
 - Attempting to get cache from ftp://ftp.ensembl.org/pub/release-93/variation/VEP
 - Looking at version 93
 - Attempting to connect to the FTP host as user anonymous
 - Successfully connected
Could not get current species list - using predefined list instead
For more species, see http://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#pre
ERROR: No matching species found at INSTALL.pl line 1123.
```

homo sapiens
config: https://github.com/mskcc/vcf2maf/blob/f8b1f58161e9c10e949f520eadae09751f65f344/.travis.yml
build: https://travis-ci.org/mskcc/vcf2maf/builds/422368913

**Comment by aparton** [comment]
Hiya,
Thanks for the reports. The debugging branch gave us a little more insight, but still no solution yet I’m afraid. I’ve added a couple more debugging lines and a potential (if unlikely) fix to the install script on the rel93-installtest branch, could you please try and run it again for s_cerevisiae and send me the output again?

Thanks,
Andrew

**Comment by evanbiederstedt** [comment]
Hi @aparton 

Thank you for the updates. 

>  I’ve added a couple more debugging lines and a potential (if unlikely) fix to the install script on the rel93-installtest branch, could you please try and run it again for s_cerevisiae and send me the output again?

I have that build here: 
https://travis-ci.org/mskcc/vcf2maf/builds/422507890

```
All tests successful.
Files=40, Tests=1690, 85 wallclock secs ( 0.33 usr  0.10 sys + 82.33 cusr  3.59 csys = 86.35 CPU)
Result: PASS
 - OK!
 - getting list of available cache files
 - Attempting to get cache from ftp://ftp.ensembl.org/pub/release-93/variation/VEP
 - Looking at version 93
 - Attempting to connect to the FTP host as user anonymous
 - Successfully connected
 - directory list pub/release-93/variation/VEP
 - Attempting to change directory to pub
 - Attempting to change directory to release-93
 - Attempting to change directory to variation
 - Attempting to change directory to VEP
Could not get current species list - using predefined list instead
For more species, see http://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#pre
ERROR: No matching species found at INSTALL.pl line 1127.
```

I'm happy to revise config scripts/rebuild! It's fascinating that the tests failed if I manually install htslib...

**Comment by evanbiederstedt** [comment]
Hi @at7 @aparton 

Here is the update using `git clone -b rel93-installtest --single-branch https://github.com/aparton/ensembl-vep.git` for the assembly `homo sapiens`. 

It's a different error. 

travis config: https://github.com/mskcc/vcf2maf/blob/f8b1f58161e9c10e949f520eadae09751f65f344/.travis.yml
build: 
https://travis-ci.org/mskcc/vcf2maf/builds/422368913

Here is the error...

https://travis-ci.org/mskcc/vcf2maf/builds/422368913#L1973-L1994

```
All tests successful.
Files=40, Tests=1690, 82 wallclock secs ( 0.36 usr  0.08 sys + 79.16 cusr  4.13 csys = 83.73 CPU)
Result: PASS
 - OK!
 - getting list of available cache files
 - Attempting to get cache from ftp://ftp.ensembl.org/pub/release-93/variation/VEP
 - Looking at version 93
 - Attempting to connect to the FTP host as user anonymous
 - Successfully connected
 - downloading ftp://ftp.ensembl.org/pub/release-93/variation/VEP/homo_sapiens_vep_93_GRCh37.tar.gz
curl failed (227), trying to fetch using LWP::Simple
 - unpacking homo_sapiens_vep_93_GRCh37.tar.gz
 - converting cache, this may take some time but will allow VEP to look up variants and frequency data much faster
 - use CTRL-C to cancel if you do not wish to convert this cache now (you may run convert_cache.pl later)
2018-08-30 04:30:40 - Processing homo_sapiens
2018-08-30 04:30:40 - Processing version 93_GRCh37
2018-08-30 04:30:40 - Processing _var cache type
[===========================================================]  [ 100% ]
2018-08-30 05:55:55 - All done!
WARNING: Changing FTP URL for GRCh37
WARNING: No download found for homo_sapiens
```

And the build actually fails here, as vcf2maf cannot find the reference. 

So, it starts to download...something. Unlike the s. cerevisiae assembly build

**Comment by aparton** [comment]
Hiya,

Thanks for these, slowly getting somewhere!

It looks like the Net::FTP perl module is failing to get a directory listing within our cache files dir. The installer seems to correctly find the FTP site, and the correct folder but is unable to generate a list of the files in there.

In short, it looks like your firewall is causing passive FTP to fail at this stage. I’ve just pushed a change to the rel93-installtest branch to disable passive mode, and that may or may not fix your issue. Could you please try it again and let me know what happens?

Regarding the successful download of homo_sapiens data, we have failsafes within the installer for some of our more popular species - however as the human cache is so large then I imagine you don’t want to be downloading this every time as part of your CI processes.

Kind Regards,
Andrew

**Comment by evanbiederstedt** [comment]
Hi @aparton @at7 

Thank you for the continued help. 

> I’ve just pushed a change to the rel93-installtest branch to disable passive mode, and that may or may not fix your issue. Could you please try it again and let me know what happens?

Here is the build:
https://travis-ci.org/mskcc/vcf2maf/builds/423061597

Error: 
```
All tests successful.
Files=40, Tests=1690, 81 wallclock secs ( 0.34 usr  0.08 sys + 78.74 cusr  3.67 csys = 82.83 CPU)
Result: PASS
 - OK!
 - getting list of available cache files
 - Attempting to get cache from ftp://ftp.ensembl.org/pub/release-93/variation/VEP
 - Looking at version 93
 - Attempting to connect to the FTP host as user anonymous
 - Successfully connected
 - directory list pub/release-93/variation/VEP
 - Attempting to change directory to pub
 - Attempting to change directory to release-93
ERROR: Could not change directory to release-93
```

> In short, it looks like your firewall is causing passive FTP to fail at this stage.

You mean, the Travis-CI firewall? 

> however as the human cache is so large then I imagine you don’t want to be downloading this every time as part of your CI processes.

Exactly. It takes far too long. This is why I'm trying s. cerevisiae, which is far smaller than GRCh37.
I'm happy to try something else if it would make more sense!

Here is the homo sapiens build, with a similar error:
https://travis-ci.org/mskcc/vcf2maf/builds/423061597

**Comment by evanbiederstedt** [comment]
Hi @at7 @aparton 

> In short, it looks like your firewall is causing passive FTP to fail at this stage. 

I think if it's the Travis-CI firewall, we should be able to contact support.

**Comment by evanbiederstedt** [comment]
Hi @at7 @aparton 

After speaking with Travis-CI support, it appears there's some issues with using `sudo` with the Travis-CI builds. 

So, I removed the use of `sudo` in the configuration script. 

Using the rel93-installtest branch, here is the issue I see:

```
All tests successful.
Files=40, Tests=1690, 100 wallclock secs ( 0.25 usr  0.09 sys + 94.69 cusr  3.86 csys = 98.89 CPU)
Result: PASS
 - OK!
 - getting list of available cache files
 - Attempting to get cache from ftp://ftp.ensembl.org/pub/release-93/variation/VEP
 - Looking at version 93
 - Attempting to connect to the FTP host as user anonymous
 - Successfully connected
 - directory list pub/release-93/variation/VEP
 - Attempting to change directory to pub
 - Attempting to change directory to release-93
ERROR: Could not change directory to release-93
```
Build: https://travis-ci.org/mskcc/vcf2maf/builds/425329424
config: https://github.com/mskcc/vcf2maf/blob/0d6188b98d39517dca628b11a5df5841698719af/.travis.yml

I'll try the master branch as well.

**Comment by evanbiederstedt** [comment]
Hi @at7 @aparton 

Is there anything else I could do on my end with regards to debugging this issue? 

Do you have other advice for how to tackle this?

Thanks!

**Comment by at7** [comment]
@evanbiederstedt I'm very sorry for the delay. We don't have a solution at the moment. I was wondering if installing the cache as a separate step would work. As described [here](http://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#cache). What is it that you want to test?

**Comment by aparton** [comment]
Hi Evan,

Apologies for the delay. I’ve been out of the office for the last couple of weeks and I wanted to take a proper look at the new error message before I responded, but it’s taken me longer than I intended. 

While the removal of sudo has solved part of your issue, it still looks like a firewall problem, and some kind of incompatibility between the perl Net::FTP library and the Travis-CI firewall. The VEP installer is looking in the correct place for the relevant cache files, however Net::FTP is failing find the relevant directory on the FTP site due to the Travis-CI firewall. Before the removal of sudo, it was finding the correct directory but not returning the list of available cache files, so while the different error message is interesting, then fundamentally it looks like the same issue.

There are two potential solutions here, depending on precisely what you aim to do. There is a failsafe in the installer that allows for the downloading of our more common cache files - does it work for you currently if you download danio_rerio instead? If it does work, although it uses a slightly different code-path to download the cache, it would be possible for me to add saccharomyces_cerevisiae to that list which may allow you to download the cache file and proceed, which may work for what you’re trying to do.

Failing that, then it would require a significant rewrite of the code that connects to the FTP site to include another failsafe. While this is possible, it wouldn’t be done quickly and currently I couldn’t provide an estimation of when it would be finished, so I’m hoping it doesn’t come to that.

Sorry that I couldn’t be of more help.

Kind Regards,
Andrew

**Comment by evanbiederstedt** [comment]
Apologies for the delays

@at7, thanks! I'lll manually installing the cache. The main goal is to test vcf2maf, with some sort of assembly. Given how long it takes to download hg18, I was going to try a smaller genome.

@aparton I will e-mail Travis-CI about the Firewall issue. In principle, there should be a solution which could be configured. 

> does it work for you currently if you download danio_rerio instead?

I think I tried this in a previous build, but this was using sudo. In principle, the exact genome doesn't matter---my motivation for trying an assembly smaller than hg18 was primarily to reduce the time of the tests. 

> Failing that, then it would require a significant rewrite of the code that connects to the FTP site to include another failsafe. While this is possible, it wouldn’t be done quickly and currently I couldn’t provide an estimation of when it would be finished, so I’m hoping it doesn’t come to that.

Exactly. I'll try the other options before something like this.

Thank you both for the help! Much appreciated

**Comment by aparton** [comment]
Hi,

I'm going to close this issue now - if you would like more support with this problem then please open a new ticket.

Kind Regards,
Andrew
