### ISSUE TITLE
Cannot connect to the Ensembl MySQL server at ensembldb.ensembl.org:3306

### ISSUE THREAD

**Issue by PlatonB** [Ensembl/ensembl-vep#603]
Elementary OS 5.0
VEP script 97
MySQL 5.7.27

Trying to annotate a simple test data set:
`sudo docker run -t -i -v $HOME/vep_data:/opt/vep/.vep ensemblorg/ensembl-vep`

`./vep --cache --merged --vcf --force_overwrite -e --dir_cache /opt/vep/.vep/ -i /opt/vep/.vep/input/VEP_input.txt -o /opt/vep/.vep/output/VEP_output.vcf`
```
DBI connect('host=ensembldb.ensembl.org;port=3306','anonymous',...) failed: Can't connect to MySQL server on 'ensembldb.ensembl.org' (111) at /opt/vep/src/ensembl-vep/Bio/EnsEMBL/Registry.pm line 1770.

-------------------- EXCEPTION --------------------
MSG: Cannot connect to the Ensembl MySQL server at ensembldb.ensembl.org:3306; check your settings & DBI error message: Can't connect to MySQL server on 'ensembldb.ensembl.org' (111)
STACK Bio::EnsEMBL::Registry::load_registry_from_db /opt/vep/src/ensembl-vep/Bio/EnsEMBL/Registry.pm:1770
STACK Bio::EnsEMBL::VEP::BaseVEP::registry /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseVEP.pm:252
STACK Bio::EnsEMBL::VEP::BaseRunner::setup_db_connection /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:120
STACK Bio::EnsEMBL::VEP::Runner::init /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:118
STACK Bio::EnsEMBL::VEP::Runner::run /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:194
STACK toplevel ./vep:223
Date (localtime)    = Wed Sep 18 17:05:26 2019
Ensembl API version = 97
---------------------------------------------------
```

`exit`

Some actions from the corresponding debugging guide:
`mysql --host=ensembldb.ensembl.org --port=3306 --user=anonymous`
`ERROR 2003 (HY000): Can't connect to MySQL server on 'ensembldb.ensembl.org' (111)`

`ping -c 5 ensembldb.ensembl.org`
```
PING ensembldb.ebi.ac.uk (193.62.193.10) 56(84) bytes of data.
64 bytes from ensembldb.ebi.ac.uk (193.62.193.10): icmp_seq=1 ttl=239 time=136 ms
64 bytes from ensembldb.ebi.ac.uk (193.62.193.10): icmp_seq=2 ttl=239 time=143 ms
64 bytes from ensembldb.ebi.ac.uk (193.62.193.10): icmp_seq=3 ttl=239 time=113 ms
64 bytes from ensembldb.ebi.ac.uk (193.62.193.10): icmp_seq=4 ttl=239 time=140 ms
64 bytes from ensembldb.ebi.ac.uk (193.62.193.10): icmp_seq=5 ttl=239 time=120 ms

--- ensembldb.ebi.ac.uk ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4005ms
rtt min/avg/max/mdev = 113.167/131.004/143.928/11.970 ms
```

**Comment by aparton** [comment]
Hi,

Thank you for this report, we’ve had some issues with our public human variation database since Wednesday and we are currently investigating. I’ll let you know when we have a fix in place.

In the meantime, you can still run VEP in offline mode - https://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#offline <https://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#offline>

Kind Regards,
Andrew

**Comment by PlatonB** [comment]
In version 98, this error no longer occurs. Issue #616 is actual now.

**Comment by PlatonB** [comment]
Bug is reproducing again.

**Comment by aparton** [comment]
Hi,

I've had a quick look and I can successfully connect to both 97 and 98 databases on ensembldb.ensembl.org - could you please send me the VEP version you're using and your VEP command?

Kind Regards,
Andrew

**Comment by PlatonB** [comment]
98.

`sudo docker run -t -i -v $HOME/vep_data:/opt/vep/.vep:Z ensemblorg/ensembl-vep`

`./vep --cache --merged --vcf --force_overwrite -e --dir_cache /home/platon/vep_data/ -i /home/platon/vep_data/input/test_input.txt -o /home/platon/vep_data/output/test_output.vcf`

**Comment by aparton** [comment]
Hi,

Thanks for the report, unfortunately I've been unable to reproduce the error however.

Could you please confirm that you're still seeing the 'Cannot connect to the Ensembl MySQL server at ...' error message? You may have been unfortunate enough to query the public database during a blip that has since been fixed.

Kind Regards,
Andrew

**Comment by PlatonB** [comment]
There's no such problem today.

**Comment by aparton** [comment]
Hi,

I'm going to close this issue now, if this issue crops up again please feel free to reopen it and we can investigate further.

Kind Regards,
Andrew

**Comment by matmu** [comment]
I issue came up again today:

```
 DBD::mysql::st execute failed: Lost connection to MySQL server during query at /opt/vep/src/ensembl-vep/Bio/EnsEMBL/DBSQL/BaseAdaptor.pm line 481.

-------------------- EXCEPTION --------------------
MSG: Detected an error whilst executing SQL 'SELECT  v.variation_id, v.name AS v_name, v.class_attrib_id AS v_class_attrib_id, v.source_id AS v_source_id, v.somatic AS v_somatic, v.flipped AS v_flipped, vs.name AS vs_name, s2.name AS vs_source_name, v.minor_allele, v.minor_allele_freq, v.minor_allele_count, v.clinical_significance, v.evidence_attribs 
FROM (( (variation v, source s1) 
  LEFT JOIN variation_synonym vs ON v.variation_id = vs.variation_id ) 
  LEFT JOIN source s2 ON vs.source_id = s2.source_id ) 
 WHERE v.name = ?  AND
       
        s1.source_id = v.source_id
     
': DBD::mysql::st execute failed: Lost connection to MySQL server during query at /opt/vep/src/ensembl-vep/Bio/EnsEMBL/DBSQL/BaseAdaptor.pm line 481.

STACK Bio::EnsEMBL::DBSQL::BaseAdaptor::generic_fetch /opt/vep/src/ensembl-vep/Bio/EnsEMBL/DBSQL/BaseAdaptor.pm:482
STACK Bio::EnsEMBL::Variation::DBSQL::VariationAdaptor::fetch_by_name /opt/vep/src/ensembl-vep/Bio/EnsEMBL/Variation/DBSQL/VariationAdaptor.pm:554
STACK Bio::EnsEMBL::VEP::Parser::ID::create_VariationFeatures /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Parser/ID.pm:162
STACK Bio::EnsEMBL::VEP::Parser::next /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Parser.pm:175
STACK Bio::EnsEMBL::VEP::InputBuffer::next /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/InputBuffer.pm:210
STACK Bio::EnsEMBL::VEP::Runner::_buffer_to_output /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:396
STACK Bio::EnsEMBL::VEP::Runner::next_output_line /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:364
STACK Bio::EnsEMBL::VEP::Runner::run /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:202
STACK toplevel /opt/vep/src/ensembl-vep/vep:224
Date (localtime)    = Wed Apr 15 12:20:20 2020
Ensembl API version = 99
---------------------------------------------------
The command '/bin/sh -c perl INSTALL.pl         --AUTO fcp         --ASSEMBLY GRCh38         --PLUGINSDIR /opt/vep/.vep/Plugins/         --CACHEDIR /opt/vep/.vep/         --PLUGINS all         --SPECIES homo_sapiens_merged &&     vep -id rs699       --cache       --nearest symbol       -o 'STDOUT'       --merged       --no_stats       > /dev/null' returned a non-zero code: 2
```

**Comment by aparton** [comment]
Hi @matmu,

Thanks for this report. This error message is normally seen when our database servers are under increased load, and we are currently running in a reduced functionality mode as described here: http://www.ensembl.info/2020/02/18/reduced-functionality-16th-25th-march-2020/

If you try again at another time when our database server is less busy then it should resolve your problem. If not, please let me know and I'll investigate further.

Kind Regards, 
Andrew

**Comment by vasicek58** [comment]
Apologies for the long silence, it turned out to be an issue on our side. Thanks for your reply!

**Comment by daniel-hui** [comment]
Sorry to necro this thread but I am having this issue now. The exact command I used 6 months ago, which was working then, is giving this error now. I tried it last Friday and today, so perhaps it is not just due to Ensembl's database servers being under load this whole time. Here is the command with paths changed:

`for i in {1..22}; do bsub -o vep_all_chromosomes/base_rv_pick_allele_reg_tab_chr"$i".o -e vep_all_chromosomes/base_rv_pick_allele_reg_tab_chr"$i".e "export PERL5LIB=$PERL5LIB:$HOME/cpanm/lib/perl5 ; time ~/tools/ensembl-vep/vep --cache --pick_allele -i descriptives/A6K/chr"$i"_notSVM_A6K.vcf.gz --fork 4 --compress_output gzip --tab --symbol --regulatory --biotype --af --af_1kg --af_gnomad --variant_class --custom gerp_conservation_scores.homo_sapiens.GRCh38.bw,GERP,bigwig --plugin SpliceAI,snv=spliceai_scores.raw.snv.hg38.vcf.gz,indel=spliceai_scores.raw.indel.hg38.vcf.gz --plugin REVEL,new_tabbed_revel_grch38.tsv.gz --plugin Mastermind,mastermind_cited_variants_reference-2021.08.03-grch38.vcf.gz --custom clinvar.vcf.gz,ClinVar,vcf,exact,0,CLNSIG,CLNREVSTAT,CLNDN -o vep_all_chromosomes/base_rv_pick_allele_reg_tab_chr"$i""; done`

Error:
```
DBI connect('host=ensembldb.ensembl.org;port=3306','anonymous',...) failed: Can't connect to MySQL server on 'ensembldb.ensembl.org' (110) at /home/dahui/tools/ensembl-vep/Bio/EnsEMBL/Registry.pm line 1771.

-------------------- EXCEPTION --------------------
MSG: Cannot connect to the Ensembl MySQL server at ensembldb.ensembl.org:3306; check your settings & DBI error message: Can't connect to MySQL server on 'ensembldb.ensembl.org' (110)
STACK Bio::EnsEMBL::Registry::load_registry_from_db /home/dahui/tools/ensembl-vep/Bio/EnsEMBL/Registry.pm:1771
STACK Bio::EnsEMBL::VEP::BaseVEP::registry /home/dahui/tools/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseVEP.pm:252
STACK Bio::EnsEMBL::VEP::BaseRunner::setup_db_connection /home/dahui/tools/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:120
STACK Bio::EnsEMBL::VEP::Runner::init /home/dahui/tools/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:123
STACK Bio::EnsEMBL::VEP::Runner::run /home/dahui/tools/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:199
STACK toplevel /home/dahui/tools/ensembl-vep/vep:232
Date (localtime)    = Mon Jun  6 12:27:09 2022
Ensembl API version = 104
---------------------------------------------------
```

Thanks.

**Comment by nuno-agostinho** [comment]
Hey @daniel-hui, good morning! Are you still having these issues?

**Comment by cksruthi** [comment]
Hi. I am getting a similar error while running VEP.

>DBI connect('host=ensembldb.ensembl.org;port=3306','anonymous',...) failed: Can't connect to MySQL server on 'ensembldb.ensembl.org:3306' (110) at /home/sruthi/Softwares/ensembl-vep-release-105/Bio/EnsEMBL/Registry.pm line 1771.

>-------------------- EXCEPTION --------------------
MSG: Cannot connect to the Ensembl MySQL server at ensembldb.ensembl.org:3306; check your settings & DBI error message: Can't connect to MySQL server on 'ensembldb.ensembl.org:3306' (110)
STACK Bio::EnsEMBL::Registry::load_registry_from_db /home/sruthi/Softwares/ensembl-vep-release-105/Bio/EnsEMBL/Registry.pm:1771
STACK Bio::EnsEMBL::VEP::BaseVEP::registry /home/sruthi/Softwares/ensembl-vep-release-105/modules/Bio/EnsEMBL/VEP/BaseVEP.pm:252
STACK Bio::EnsEMBL::VEP::BaseRunner::setup_db_connection /home/sruthi/Softwares/ensembl-vep-release-105/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:120
STACK Bio::EnsEMBL::VEP::Runner::init /home/sruthi/Softwares/ensembl-vep-release-105/modules/Bio/EnsEMBL/VEP/Runner.pm:123
STACK Bio::EnsEMBL::VEP::Runner::run /home/sruthi/Softwares/ensembl-vep-release-105/modules/Bio/EnsEMBL/VEP/Runner.pm:199
STACK toplevel /home/sruthi/Softwares/ensembl-vep-release-105/vep:232
Date (localtime)    = Thu Jul 28 09:40:05 2022
Ensembl API version = 105
---------------------------------------------------

The command used was:
>vep --cache --merged --dir_cache ~/Softwares/vepcache/ --fork 4 --input_file inputfile --output_file outputfile --everything --exclude_predicted --total_length --show_ref_allele --check_existing --exclude_null_alleles --clin_sig_allele 1 --flag_pick --force_overwrite --no_stats --vcf --buffer_size 2000

I have tried running this multiple times since yesterday and have been getting the same error.

**Comment by nuno-agostinho** [comment]
Hey @cksruthi!

Due to maintenance work, the Ensembl services were temporarily unavailable for some time during Tuesday and Wednesday: https://www.ensembl.info/2022/07/20/disruption-to-ensembl-services-4/

Unfortunately, the Ensembl database is still down and we are working to fix it as soon as possible. I am sorry for the inconvenience.

Kind regards,
Nuno

**Comment by cksruthi** [comment]
@nuno-agostinho Thank you very much for the quick response.

**Comment by dhruti89** [comment]
@nuno-agostinho Is the Ensembl database still down? I am still getting this error.

**Comment by nuno-agostinho** [comment]
Hey @dhruti89!

Unfortunately, the Ensembl database is still down and we are investigating this issue.

In the meanwhile, please try setting VEP `--host` argument to connect to the Ensembl database mirrors from USA (`useastdb.ensembl.org`) or Asia (`asiadb.ensembl.org`): http://www.ensembl.org/info/data/mysql.html

We are trying to get the Ensembl database back online soon. Sorry for the inconvenience.

Best regards,
Nuno

**Comment by dhruti89** [comment]
Thanks @nuno-agostinho for the quick revert and the workaround

**Comment by fridells51** [comment]
@nuno-agostinho Are the database connectivity issues still persisting? Same VEP command was working yesterday, and today it's not. I've tried every available configuration of hosts and ports in the page you linked 2 days ago.

**Comment by nuno-agostinho** [comment]
Hey @fridells51,

I'm sorry to hear that. All Ensembl servers should be working now. You can test the connection to our database with the following MySQL command:

```
mysql -h ensembldb.ensembl.org -u anonymous
```

What is the VEP output that you are getting?

Thanks,
Nuno

**Comment by fridells51** [comment]
Hi Nuno, 

Thanks for the reply. This is the command I'm running (vep installed in an active conda environment) `vep -i results/annotated/all.vcf.gz --plugin GO,MF,BP  --database  --fasta references/GRCh38.fa.gz`

And this is the output 

```
Possible precedence issue with control flow operator at /gpfs/gsfs10/users/NICHD-core0/analysis/stratakis/pam-wes/env/lib/site_perl/5.26.2/Bio/DB/IndexedBase.pm line 805.
DBI connect('host=ensembldb.ensembl.org;port=3306','anonymous',...) failed: Unknown MySQL server host 'ensembldb.ensembl.org' (2) at /gpfs/gsfs10/users/NICHD-core0/analysis/stratakis/pam-wes/env/share/ensembl-vep-104.3-0/Bio/EnsEMBL/Registry.pm line 1771.

-------------------- EXCEPTION --------------------
MSG: Cannot connect to the Ensembl MySQL server at ensembldb.ensembl.org:3306; check your settings & DBI error message: Unknown MySQL server host 'ensembldb.ensembl.org' (2)
STACK Bio::EnsEMBL::Registry::load_registry_from_db /gpfs/gsfs10/users/NICHD-core0/analysis/stratakis/pam-wes/env/share/ensembl-vep-104.3-0/Bio/EnsEMBL/Registry.pm:1771
STACK Bio::EnsEMBL::VEP::BaseVEP::registry /gpfs/gsfs10/users/NICHD-core0/analysis/stratakis/pam-wes/env/share/ensembl-vep-104.3-0/modules/Bio/EnsEMBL/VEP/BaseVEP.pm:252
STACK Bio::EnsEMBL::VEP::BaseRunner::setup_db_connection /gpfs/gsfs10/users/NICHD-core0/analysis/stratakis/pam-wes/env/share/ensembl-vep-104.3-0/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:120
STACK Bio::EnsEMBL::VEP::Runner::init /gpfs/gsfs10/users/NICHD-core0/analysis/stratakis/pam-wes/env/share/ensembl-vep-104.3-0/modules/Bio/EnsEMBL/VEP/Runner.pm:123
STACK Bio::EnsEMBL::VEP::Runner::run /gpfs/gsfs10/users/NICHD-core0/analysis/stratakis/pam-wes/env/share/ensembl-vep-104.3-0/modules/Bio/EnsEMBL/VEP/Runner.pm:199
STACK toplevel /gpfs/gsfs10/users/NICHD-core0/analysis/stratakis/pam-wes/env/bin/vep:232
Date (localtime)    = Thu Aug  4 14:28:58 2022
Ensembl API version = 104
---------------------------------------------------
```

**Comment by nuno-agostinho** [comment]
Hi @fridells51,

In your case, I would suggest to check if you have all the dependencies you need to run VEP installed when running the job in HPC.

If your HPC supports running Singularity/Docker containers, you can also use [the official VEP image](https://hub.docker.com/r/ensemblorg/ensembl-vep) that comes with all the dependencies already set up.

Feel free to reach me if you need help from our side!

Best regards,
Nuno

**Comment by daniel-hui** [comment]
Hi @nuno-agostinho, 

I tried again today and am still having the same issue. I tried `mysql -h ensembldb.ensembl.org -u anonymous` and it gives the error `ERROR 2003 (HY000): Can't connect to MySQL server on 'ensembldb.ensembl.org' (110)`, I tried setting -h to useastdb.ensembl.org and asiadb.ensembl.org and it still gave the same error. Would you know some other steps to try next? Thanks.

**Comment by nakib103** [comment]
Hello @daniel-hui,

Thanks for your query! 

I can see the database is up - 
```
% mysql -h ensembldb.ensembl.org -u anonymous --silent 
mysql> 
```

Were you able to connect to the database before or is it your first time connecting? It might be worthwhile to check if your network is blocking this connection.

Best regards,
Nakib

**Comment by Duong-NguyenTrinhTrung** [comment]
Hi @nuno-agostinho 

I am sorry for bringing this back again. I have experience this problem yesterday and it is still today.

"DBI connect('host=ensembldb.ensembl.org;port=3306','anonymous',...) failed: Lost connection to MySQL server at 'reading initial communication packet', system error: 104 at /home/username/veptool/share/ensembl-vep-106.1-0/Bio/EnsEMBL/Registry.pm line 1771." Could I bother you to check it? Thanks in advance!

**Comment by nuno-agostinho** [comment]
Hi @Duong-NguyenTrinhTrung,

Can you try again today? Could you also try connecting to one of the mirrors in http://www.ensembl.org/info/data/mysql.html (`useastdb.ensembl.org ` or `asiadb.ensembl.org `) using the argument `--host` in VEP?

Thank you!

All the best,
Nuno

**Comment by Duong-NguyenTrinhTrung** [comment]
Hi @nuno-agostinho

Thanks for the reply. I have tried 2 alternative mirrors which different ports but still could not connect. The error message is:

DBI connect('host=asiadb.ensembl.org;port=5306','anonymous',...) failed: Lost connection to MySQL server at 'reading authorization packet', system error: 104 at /home/ljw303/veptool/share/ensembl-vep-106.1-0/Bio/EnsEMBL/Registry.pm line 1771.


To be clear, could you take a look to see if my VEP command is not appropriate?

vep  -i   VEP.input --host asiadb.ensembl.org --port 5306   -o    VEP.output   --cache --dir_cache path_to_cache   --dir_plugins.  /path_to_plugins/   --plugin dbNSFP,/path_to_plugins/dbNSFP4.2a.gz,SIFT_score,SIFT4G_score,Polyphen2_HDIV_score,Polyphen2_HVAR_score,LRT_score,LRT_pred,LRT_Omega.  --force_overwrite

**Comment by Duong-NguyenTrinhTrung** [comment]
Hi @nuno-agostinho,

When I run the commands you suggested:

mysql -h ensembldb.ensembl.org -u anonymous --silent
mysql -h useastdb.ensembl.org -u anonymous --silent
mysql -h asiadb.ensembl.org -u anonymous --silent 

I got an error message saying: "-bash: mysql: command not found". It is weird and I have no idea about this error. I supposed that I have mysql installed as I have run VEP for many times last month. 

Furthermore, I install  VEP via conda and this is my conda package (command: conda list):
[VEP_conda_packages.txt](https://github.com/Ensembl/ensembl-vep/files/10153700/VEP_conda_packages.txt)

Could you help me to take a look? Many thanks!

**Comment by nuno-agostinho** [comment]
Hi @Duong-NguyenTrinhTrung,

It's indeed weird that you were able to use the databases before and now they are not working.

VEP via conda is not an official distribution and we cannot offer support for it. I would recommend instead using our official VEP image for [Docker](https://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#docker) or [Singularity](https://www.ensembl.org/info/docs/tools/vep/script/vep_download.html#singularity).

Please tell me if you have any further issues with this approach.

Thanks,
Nuno

**Comment by Duong-NguyenTrinhTrung** [comment]
Hi @nuno-agostinho,

Thanks for your reply. The conda approach worked well for me over the last month. Are you sure that there is no problem with the database on your side? I am using a node in HPC and conda is the best way for me to install VEP.

**Comment by Duong-NguyenTrinhTrung** [comment]
Hi @nuno-agostinho,

I have installed mysql-client and test the connection to all the databases but none was successful (image attached)

mysql -h ensembldb.ensembl.org -u anonymous --silent
mysql -h useastdb.ensembl.org -u anonymous --silent
mysql -h asiadb.ensembl.org -u anonymous --silent

<img width="1300" alt="image" src="https://user-images.githubusercontent.com/98522729/205667516-3a8e62ae-1624-457e-ae56-2da9d1268e58.png">

Could you take a look at it? Thanks!

**Comment by nuno-agostinho** [comment]
Hey @Duong-NguyenTrinhTrung,

We haven't had reports from other users having these specific issues and all seems fine in our end. This leads me to believe that there are issues with firewall permissions or other networking problems on the network that you are trying to connect from. Have you tried to connect to these databases outside of your institute/company network (or turning off your VPN if that's your case)?

I would suggest to contact your IT team to discuss these issues. Please do tell me if these issues persist.

Best,
Nuno

**Comment by sruthisrini** [comment]
Hello, 

I got this error today

DBD::mysql::st execute failed: Table 'seq_region' is marked as crashed and should be repaired at /Users/sruthisrinivasan/perl5/ensembl-vep/Bio/EnsEMBL/DBSQL/CoordSystemAdaptor.pm line 261.
DBD::mysql::st execute failed: Table 'seq_region' is marked as crashed and should be repaired at /Users/sruthisrinivasan/perl5/ensembl-vep/Bio/EnsEMBL/DBSQL/CoordSystemAdaptor.pm line 261.

So far, I was not getting errors like these and the output files were generating. Is this because of the server problem?

**Comment by nakib103** [comment]
Hello @sruthisrini 

Thanks for reporting it to us, we are already looking into it. We will let you once we have a update.

Best regards,
Nakib

**Comment by nuno-agostinho** [comment]
Hey @sruthisrini, other users have reported this issue in https://github.com/Ensembl/ensembl-vep/issues/1452. We are investigating the issue and will post updates there.

Thanks,
Nuno

**Comment by sruthisrini** [comment]
@nakib103 It is working now. Thanks for fixing soon!

**Comment by sruthisrini** [comment]
Hello,

I got this error today and this is the first time I am getting this error while running the below code:
`/vep -i input.vcf -o output.vcf --cache --force_overwrite --tab --no_check_variants_order --force --plugin GeneSplicer,/genesplicer,/GeneSplicer/human --plugin SpliceAI,snv=spliceai_scores.raw.snv.hg38.vcf.gz,indel=spliceai_scores.raw.indel.hg38.vcf.gz,cutoff=0.5 --sift b --polyphen p`

```
install_driver(mysql) failed: Can't load '/Users/sruthisrinivasan/perl5/perlbrew/perls/5.26.2/lib/site_perl/5.26.2/darwin-thread-multi-2level/auto/DBD/mysql/mysql.bundle' for module DBD::mysql: dlopen(/Users/sruthisrinivasan/perl5/perlbrew/perls/5.26.2/lib/site_perl/5.26.2/darwin-thread-multi-2level/auto/DBD/mysql/mysql.bundle, 0x0001): Library not loaded: '/usr/local/opt/mysql/lib/libmysqlclient.21.dylib'
  Referenced from: '/Users/sruthisrinivasan/perl5/perlbrew/perls/5.26.2/lib/site_perl/5.26.2/darwin-thread-multi-2level/auto/DBD/mysql/mysql.bundle'
  Reason: tried: '/usr/local/opt/mysql/lib/libmysqlclient.21.dylib' (no such file), '/usr/local/lib/libmysqlclient.21.dylib' (no such file), '/usr/lib/libmysqlclient.21.dylib' (no such file), '/usr/local/Cellar/mysql/8.1.0/lib/libmysqlclient.21.dylib' (no such file), '/usr/local/lib/libmysqlclient.21.dylib' (no such file), '/usr/lib/libmysqlclient.21.dylib' (no such file) at /Users/sruthisrinivasan/perl5/perlbrew/perls/5.26.2/lib/5.26.2/darwin-thread-multi-2level/DynaLoader.pm line 197.
 at (eval 34) line 3.
Compilation failed in require at (eval 34) line 3.
Perhaps a required shared library or dll isn't installed where expected
 at /Users/sruthisrinivasan/perl5/ensembl-vep/Bio/EnsEMBL/Registry.pm line 1771.
```

Could you please let me know how to solve this issue?

**Comment by chan-98** [comment]
Hello, went through this issue and I'm still unable to use the tool. I'm running it from inside docker:

```
docker run -it --rm -u `id -u`:`id -g` -v $PWD:/opt/vep/.vep ensemblorg/ensembl-vep bash

I have no name!@42c04059f3b2:/opt/vep/.vep$ vep -i S1.combined.vcf -o S1.combined.vep.vcf --species homo_sapiens --cache
DBI connect('host=ensembldb.ensembl.org;port=3306','anonymous',...) failed: Can't connect to MySQL server on 'ensembldb.ensembl.org:3306' (110) at /opt/vep/src/ensembl-vep/Bio/EnsEMBL/Registry.pm line 1771.

-------------------- EXCEPTION --------------------
MSG: Cannot connect to the Ensembl MySQL server at ensembldb.ensembl.org:3306; check your settings & DBI error message: Can't connect to MySQL server on 'ensembldb.ensembl.org:3306' (110)
STACK Bio::EnsEMBL::Registry::load_registry_from_db /opt/vep/src/ensembl-vep/Bio/EnsEMBL/Registry.pm:1771
STACK Bio::EnsEMBL::VEP::BaseVEP::registry /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseVEP.pm:283
STACK Bio::EnsEMBL::VEP::BaseRunner::setup_db_connection /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:120
STACK Bio::EnsEMBL::VEP::Runner::init /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:123
STACK Bio::EnsEMBL::VEP::Runner::run /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:200
STACK toplevel /opt/vep/src/ensembl-vep/vep:46
Date (localtime)    = Wed Feb 28 10:12:31 2024
Ensembl API version = 111
---------------------------------------------------
```
Getting the same error still. I'm running this tool for the first time, Please guide me.

**Comment by nakib103** [comment]
Hello @chan-98,

Thanks for your query!

I cannot reproduce your issue. This works fine for me -
```
$ vep --force --id "rs699" --database  --db_version 111
```

It might be worthwhile to check if your network is not blocking this connection, for example you are behind a firewall.

Best regards,
Nakib

**Comment by chan-98** [comment]
Hello, went through this issue and I'm still unable to use the tool. I'm running it from inside docker:

```
docker run -it --rm -u `id -u`:`id -g` -v $PWD:/opt/vep/.vep ensemblorg/ensembl-vep bash

I have no name!@42c04059f3b2:/opt/vep/.vep$ vep -i S1.combined.vcf -o S1.combined.vep.vcf --species homo_sapiens --cache
DBI connect('host=ensembldb.ensembl.org;port=3306','anonymous',...) failed: Can't connect to MySQL server on 'ensembldb.ensembl.org:3306' (110) at /opt/vep/src/ensembl-vep/Bio/EnsEMBL/Registry.pm line 1771.

-------------------- EXCEPTION --------------------
MSG: Cannot connect to the Ensembl MySQL server at ensembldb.ensembl.org:3306; check your settings & DBI error message: Can't connect to MySQL server on 'ensembldb.ensembl.org:3306' (110)
STACK Bio::EnsEMBL::Registry::load_registry_from_db /opt/vep/src/ensembl-vep/Bio/EnsEMBL/Registry.pm:1771
STACK Bio::EnsEMBL::VEP::BaseVEP::registry /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseVEP.pm:283
STACK Bio::EnsEMBL::VEP::BaseRunner::setup_db_connection /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:120
STACK Bio::EnsEMBL::VEP::Runner::init /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:123
STACK Bio::EnsEMBL::VEP::Runner::run /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:200
STACK toplevel /opt/vep/src/ensembl-vep/vep:46
Date (localtime)    = Wed Feb 28 10:12:31 2024
Ensembl API version = 111
---------------------------------------------------
```
Getting the same error still. I'm running this tool for the first time, Please guide me.

**Comment by THT-sleepy** [comment]
Hello, I went this issue today, could you help?

Here is my command:
 ./vep -i examples/homo_sapiens_GRCh38.vcf --cache --force_overwrite

Here is the error message:
DBI connect('host=ensembldb.ensembl.org;port=3306','anonymous',...) failed: Unknown MySQL server host 'ensembldb.ensembl.org' (-3) at /opt/vep/src/ensembl-vep/Bio/EnsEMBL/Registry.pm line 1771.

-------------------- EXCEPTION --------------------
MSG: Cannot connect to the Ensembl MySQL server at ensembldb.ensembl.org:3306; check your settings & DBI error message: Unknown MySQL server host 'ensembldb.ensembl.org' (-3)
STACK Bio::EnsEMBL::Registry::load_registry_from_db /opt/vep/src/ensembl-vep/Bio/EnsEMBL/Registry.pm:1771
STACK Bio::EnsEMBL::VEP::BaseVEP::registry /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseVEP.pm:283
STACK Bio::EnsEMBL::VEP::BaseRunner::setup_db_connection /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/BaseRunner.pm:120
STACK Bio::EnsEMBL::VEP::Runner::init /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:123
STACK Bio::EnsEMBL::VEP::Runner::run /opt/vep/src/ensembl-vep/modules/Bio/EnsEMBL/VEP/Runner.pm:200
STACK toplevel ./vep:46
Date (localtime)    = Mon Mar 25 06:32:21 2024
Ensembl API version = 111

**Comment by THT-sleepy** [comment]
Hello @nakib103

Thank you for your help, I reran it in my own laptop(previously using cloud server, but I don't know how to change firewall setting of it) and it went well. I think you're right.

Best
Huatao
